// File: src/lib/countryCodes.ts
// Fonte: https://gist.github.com/Goles/3196253 - Adattato per TypeScript

export interface CountryCode {
    name: string;
    dial_code: string;
    code: string;
    flag: string;
}

export const countryCodes: CountryCode[] = [
	{ name: 'Italia', dial_code: '+39', code: 'IT', flag: '🇮🇹' },
	{ name: 'Stati Uniti', dial_code: '+1', code: 'US', flag: '🇺🇸' },
	{ name: 'Regno Unito', dial_code: '+44', code: 'GB', flag: '🇬🇧' },
	{ name: 'Afghanistan', dial_code: '+93', code: 'AF', flag: '🇦🇫' },
	{ name: 'Albania', dial_code: '+355', code: 'AL', flag: '🇦🇱' },
	{ name: 'Algeria', dial_code: '+213', code: 'DZ', flag: '🇩🇿' },
	{ name: 'Samoa Americane', dial_code: '+1684', code: 'AS', flag: '🇦🇸' },
	{ name: 'Andorra', dial_code: '+376', code: 'AD', flag: '🇦🇩' },
	{ name: 'Angola', dial_code: '+244', code: 'AO', flag: '🇦🇴' },
	{ name: 'Anguilla', dial_code: '+1264', code: 'AI', flag: '🇦🇮' },
	{ name: 'Antartide', dial_code: '+672', code: 'AQ', flag: '🇦🇶' },
	{ name: 'Antigua e Barbuda', dial_code: '+1268', code: 'AG', flag: '🇦🇬' },
	{ name: 'Argentina', dial_code: '+54', code: 'AR', flag: '🇦🇷' },
	{ name: 'Armenia', dial_code: '+374', code: 'AM', flag: '🇦🇲' },
	{ name: 'Aruba', dial_code: '+297', code: 'AW', flag: '🇦🇼' },
	{ name: 'Australia', dial_code: '+61', code: 'AU', flag: '🇦🇺' },
	{ name: 'Austria', dial_code: '+43', code: 'AT', flag: '🇦🇹' },
	{ name: 'Azerbaigian', dial_code: '+994', code: 'AZ', flag: '🇦🇿' },
	{ name: 'Bahamas', dial_code: '+1242', code: 'BS', flag: '🇧🇸' },
	{ name: 'Bahrein', dial_code: '+973', code: 'BH', flag: '🇧🇭' },
	{ name: 'Bangladesh', dial_code: '+880', code: 'BD', flag: '🇧🇩' },
	{ name: 'Barbados', dial_code: '+1246', code: 'BB', flag: '🇧🇧' },
	{ name: 'Bielorussia', dial_code: '+375', code: 'BY', flag: '🇧🇾' },
	{ name: 'Belgio', dial_code: '+32', code: 'BE', flag: '🇧🇪' },
	{ name: 'Belize', dial_code: '+501', code: 'BZ', flag: '🇧🇿' },
	{ name: 'Benin', dial_code: '+229', code: 'BJ', flag: '🇧🇯' },
	{ name: 'Bermuda', dial_code: '+1441', code: 'BM', flag: '🇧🇲' },
	{ name: 'Bhutan', dial_code: '+975', code: 'BT', flag: '🇧🇹' },
	{ name: 'Bolivia', dial_code: '+591', code: 'BO', flag: '🇧🇴' },
	{ name: 'Bosnia ed Erzegovina', dial_code: '+387', code: 'BA', flag: '🇧🇦' },
	{ name: 'Botswana', dial_code: '+267', code: 'BW', flag: '🇧🇼' },
	{ name: 'Brasile', dial_code: '+55', code: 'BR', flag: '🇧🇷' },
	{ name: 'Territorio britannico dell\'Oceano Indiano', dial_code: '+246', code: 'IO', flag: '🇮🇴' },
	{ name: 'Brunei', dial_code: '+673', code: 'BN', flag: '🇧🇳' },
	{ name: 'Bulgaria', dial_code: '+359', code: 'BG', flag: '🇧🇬' },
	{ name: 'Burkina Faso', dial_code: '+226', code: 'BF', flag: '🇧🇫' },
	{ name: 'Burundi', dial_code: '+257', code: 'BI', flag: '🇧🇮' },
	{ name: 'Cambogia', dial_code: '+855', code: 'KH', flag: '🇰🇭' },
	{ name: 'Camerun', dial_code: '+237', code: 'CM', flag: '🇨🇲' },
	{ name: 'Canada', dial_code: '+1', code: 'CA', flag: '🇨🇦' },
	{ name: 'Capo Verde', dial_code: '+238', code: 'CV', flag: '🇨🇻' },
	{ name: 'Isole Cayman', dial_code: '+345', code: 'KY', flag: '🇰🇾' },
	{ name: 'Repubblica Centrafricana', dial_code: '+236', code: 'CF', flag: '🇨🇫' },
	{ name: 'Ciad', dial_code: '+235', code: 'TD', flag: '🇹🇩' },
	{ name: 'Cile', dial_code: '+56', code: 'CL', flag: '🇨🇱' },
	{ name: 'Cina', dial_code: '+86', code: 'CN', flag: '🇨🇳' },
	{ name: 'Isola di Natale', dial_code: '+61', code: 'CX', flag: '🇨🇽' },
	{ name: 'Isole Cocos (Keeling)', dial_code: '+61', code: 'CC', flag: '🇨🇨' },
	{ name: 'Colombia', dial_code: '+57', code: 'CO', flag: '🇨🇴' },
	{ name: 'Comore', dial_code: '+269', code: 'KM', flag: '🇰🇲' },
	{ name: 'Congo', dial_code: '+242', code: 'CG', flag: '🇨🇬' },
	{ name: 'Repubblica Democratica del Congo', dial_code: '+243', code: 'CD', flag: '🇨🇩' },
	{ name: 'Isole Cook', dial_code: '+682', code: 'CK', flag: '🇨🇰' },
	{ name: 'Costa Rica', dial_code: '+506', code: 'CR', flag: '🇨🇷' },
	{ name: 'Costa d\'Avorio', dial_code: '+225', code: 'CI', flag: '🇨🇮' },
	{ name: 'Croazia', dial_code: '+385', code: 'HR', flag: '🇭🇷' },
	{ name: 'Cuba', dial_code: '+53', code: 'CU', flag: '🇨🇺' },
	{ name: 'Cipro', dial_code: '+357', code: 'CY', flag: '🇨🇾' },
	{ name: 'Repubblica Ceca', dial_code: '+420', code: 'CZ', flag: '🇨🇿' },
	{ name: 'Danimarca', dial_code: '+45', code: 'DK', flag: '🇩🇰' },
	{ name: 'Gibuti', dial_code: '+253', code: 'DJ', flag: '🇩🇯' },
	{ name: 'Dominica', dial_code: '+1767', code: 'DM', flag: '🇩🇲' },
	{ name: 'Repubblica Dominicana', dial_code: '+1849', code: 'DO', flag: '🇩🇴' },
	{ name: 'Ecuador', dial_code: '+593', code: 'EC', flag: '🇪🇨' },
	{ name: 'Egitto', dial_code: '+20', code: 'EG', flag: '🇪🇬' },
	{ name: 'El Salvador', dial_code: '+503', code: 'SV', flag: '🇸🇻' },
	{ name: 'Guinea Equatoriale', dial_code: '+240', code: 'GQ', flag: '🇬🇶' },
	{ name: 'Eritrea', dial_code: '+291', code: 'ER', flag: '🇪🇷' },
	{ name: 'Estonia', dial_code: '+372', code: 'EE', flag: '🇪🇪' },
	{ name: 'Etiopia', dial_code: '+251', code: 'ET', flag: '🇪🇹' },
	{ name: 'Isole Falkland (Malvine)', dial_code: '+500', code: 'FK', flag: '🇫🇰' },
	{ name: 'Isole Faroe', dial_code: '+298', code: 'FO', flag: '🇫🇴' },
	{ name: 'Fiji', dial_code: '+679', code: 'FJ', flag: '🇫🇯' },
	{ name: 'Finlandia', dial_code: '+358', code: 'FI', flag: '🇫🇮' },
	{ name: 'Francia', dial_code: '+33', code: 'FR', flag: '🇫🇷' },
	{ name: 'Guyana francese', dial_code: '+594', code: 'GF', flag: '🇬🇫' },
	{ name: 'Polinesia francese', dial_code: '+689', code: 'PF', flag: '🇵🇫' },
	{ name: 'Gabon', dial_code: '+241', code: 'GA', flag: '🇬🇦' },
	{ name: 'Gambia', dial_code: '+220', code: 'GM', flag: '🇬🇲' },
	{ name: 'Georgia', dial_code: '+995', code: 'GE', flag: '🇬🇪' },
	{ name: 'Germania', dial_code: '+49', code: 'DE', flag: '🇩🇪' },
	{ name: 'Ghana', dial_code: '+233', code: 'GH', flag: '🇬🇭' },
	{ name: 'Gibilterra', dial_code: '+350', code: 'GI', flag: '🇬🇮' },
	{ name: 'Grecia', dial_code: '+30', code: 'GR', flag: '🇬🇷' },
	{ name: 'Groenlandia', dial_code: '+299', code: 'GL', flag: '🇬🇱' },
	{ name: 'Grenada', dial_code: '+1473', code: 'GD', flag: '🇬🇩' },
	{ name: 'Guadalupa', dial_code: '+590', code: 'GP', flag: '🇬🇵' },
	{ name: 'Guam', dial_code: '+1671', code: 'GU', flag: '🇬🇺' },
	{ name: 'Guatemala', dial_code: '+502', code: 'GT', flag: '🇬🇹' },
	{ name: 'Guernsey', dial_code: '+44', code: 'GG', flag: '🇬🇬' },
	{ name: 'Guinea', dial_code: '+224', code: 'GN', flag: '🇬🇳' },
	{ name: 'Guinea-Bissau', dial_code: '+245', code: 'GW', flag: '🇬🇼' },
	{ name: 'Guyana', dial_code: '+592', code: 'GY', flag: '🇬🇾' },
	{ name: 'Haiti', dial_code: '+509', code: 'HT', flag: '🇭🇹' },
	{ name: 'Città del Vaticano', dial_code: '+379', code: 'VA', flag: '🇻🇦' },
	{ name: 'Honduras', dial_code: '+504', code: 'HN', flag: '🇭🇳' },
	{ name: 'Hong Kong', dial_code: '+852', code: 'HK', flag: '🇭🇰' },
	{ name: 'Ungheria', dial_code: '+36', code: 'HU', flag: '🇭🇺' },
	{ name: 'Islanda', dial_code: '+354', code: 'IS', flag: '🇮🇸' },
	{ name: 'India', dial_code: '+91', code: 'IN', flag: '🇮🇳' },
	{ name: 'Indonesia', dial_code: '+62', code: 'ID', flag: '🇮🇩' },
	{ name: 'Iran', dial_code: '+98', code: 'IR', flag: '🇮🇷' },
	{ name: 'Iraq', dial_code: '+964', code: 'IQ', flag: '🇮🇶' },
	{ name: 'Irlanda', dial_code: '+353', code: 'IE', flag: '🇮🇪' },
	{ name: 'Isola di Man', dial_code: '+44', code: 'IM', flag: '🇮🇲' },
	{ name: 'Israele', dial_code: '+972', code: 'IL', flag: '🇮🇱' },
	{ name: 'Giamaica', dial_code: '+1876', code: 'JM', flag: '🇯🇲' },
	{ name: 'Giappone', dial_code: '+81', code: 'JP', flag: '🇯🇵' },
	{ name: 'Jersey', dial_code: '+44', code: 'JE', flag: '🇯🇪' },
	{ name: 'Giordania', dial_code: '+962', code: 'JO', flag: '🇯🇴' },
	{ name: 'Kazakistan', dial_code: '+7', code: 'KZ', flag: '🇰🇿' },
	{ name: 'Kenya', dial_code: '+254', code: 'KE', flag: '🇰🇪' },
	{ name: 'Kiribati', dial_code: '+686', code: 'KI', flag: '🇰🇮' },
	{ name: 'Corea del Nord', dial_code: '+850', code: 'KP', flag: '🇰🇵' },
	{ name: 'Corea del Sud', dial_code: '+82', code: 'KR', flag: '🇰🇷' },
	{ name: 'Kuwait', dial_code: '+965', code: 'KW', flag: '🇰🇼' },
	{ name: 'Kirghizistan', dial_code: '+996', code: 'KG', flag: '🇰🇬' },
	{ name: 'Laos', dial_code: '+856', code: 'LA', flag: '🇱🇦' },
	{ name: 'Lettonia', dial_code: '+371', code: 'LV', flag: '🇱🇻' },
	{ name: 'Libano', dial_code: '+961', code: 'LB', flag: '🇱🇧' },
	{ name: 'Lesotho', dial_code: '+266', code: 'LS', flag: '🇱🇸' },
	{ name: 'Liberia', dial_code: '+231', code: 'LR', flag: '🇱🇷' },
	{ name: 'Libia', dial_code: '+218', code: 'LY', flag: '🇱🇾' },
	{ name: 'Liechtenstein', dial_code: '+423', code: 'LI', flag: '🇱🇮' },
	{ name: 'Lituania', dial_code: '+370', code: 'LT', flag: '🇱🇹' },
	{ name: 'Lussemburgo', dial_code: '+352', code: 'LU', flag: '🇱🇺' },
	{ name: 'Macao', dial_code: '+853', code: 'MO', flag: '🇲🇴' },
	{ name: 'Macedonia del Nord', dial_code: '+389', code: 'MK', flag: '🇲🇰' },
	{ name: 'Madagascar', dial_code: '+261', code: 'MG', flag: '🇲🇬' },
	{ name: 'Malawi', dial_code: '+265', code: 'MW', flag: '🇲🇼' },
	{ name: 'Malesia', dial_code: '+60', code: 'MY', flag: '🇲🇾' },
	{ name: 'Maldive', dial_code: '+960', code: 'MV', flag: '🇲🇻' },
	{ name: 'Mali', dial_code: '+223', code: 'ML', flag: '🇲🇱' },
	{ name: 'Malta', dial_code: '+356', code: 'MT', flag: '🇲🇹' },
	{ name: 'Isole Marshall', dial_code: '+692', code: 'MH', flag: '🇲🇭' },
	{ name: 'Martinica', dial_code: '+596', code: 'MQ', flag: '🇲🇶' },
	{ name: 'Mauritania', dial_code: '+222', code: 'MR', flag: '🇲🇷' },
	{ name: 'Mauritius', dial_code: '+230', code: 'MU', flag: '🇲🇺' },
	{ name: 'Mayotte', dial_code: '+262', code: 'YT', flag: '🇾🇹' },
	{ name: 'Messico', dial_code: '+52', code: 'MX', flag: '🇲🇽' },
	{ name: 'Stati Federati di Micronesia', dial_code: '+691', code: 'FM', flag: '🇫🇲' },
	{ name: 'Moldavia', dial_code: '+373', code: 'MD', flag: '🇲🇩' },
	{ name: 'Monaco', dial_code: '+377', code: 'MC', flag: '🇲🇨' },
	{ name: 'Mongolia', dial_code: '+976', code: 'MN', flag: '🇲🇳' },
	{ name: 'Montenegro', dial_code: '+382', code: 'ME', flag: '🇲🇪' },
	{ name: 'Montserrat', dial_code: '+1664', code: 'MS', flag: '🇲🇸' },
	{ name: 'Marocco', dial_code: '+212', code: 'MA', flag: '🇲🇦' },
	{ name: 'Mozambico', dial_code: '+258', code: 'MZ', flag: '🇲🇿' },
	{ name: 'Myanmar', dial_code: '+95', code: 'MM', flag: '🇲🇲' },
	{ name: 'Namibia', dial_code: '+264', code: 'NA', flag: '🇳🇦' },
	{ name: 'Nauru', dial_code: '+674', code: 'NR', flag: '🇳🇷' },
	{ name: 'Nepal', dial_code: '+977', code: 'NP', flag: '🇳🇵' },
	{ name: 'Paesi Bassi', dial_code: '+31', code: 'NL', flag: '🇳🇱' },
	{ name: 'Nuova Caledonia', dial_code: '+687', code: 'NC', flag: '🇳🇨' },
	{ name: 'Nuova Zelanda', dial_code: '+64', code: 'NZ', flag: '🇳🇿' },
	{ name: 'Nicaragua', dial_code: '+505', code: 'NI', flag: '🇳🇮' },
	{ name: 'Niger', dial_code: '+227', code: 'NE', flag: '🇳🇪' },
	{ name: 'Nigeria', dial_code: '+234', code: 'NG', flag: '🇳🇬' },
	{ name: 'Niue', dial_code: '+683', code: 'NU', flag: '🇳🇺' },
	{ name: 'Isola Norfolk', dial_code: '+672', code: 'NF', flag: '🇳🇫' },
	{ name: 'Isole Marianne Settentrionali', dial_code: '+1670', code: 'MP', flag: '🇲🇵' },
	{ name: 'Norvegia', dial_code: '+47', code: 'NO', flag: '🇳🇴' },
	{ name: 'Oman', dial_code: '+968', code: 'OM', flag: '🇴🇲' },
	{ name: 'Pakistan', dial_code: '+92', code: 'PK', flag: '🇵🇰' },
	{ name: 'Palau', dial_code: '+680', code: 'PW', flag: '🇵🇼' },
	{ name: 'Palestina', dial_code: '+970', code: 'PS', flag: '🇵🇸' },
	{ name: 'Panama', dial_code: '+507', code: 'PA', flag: '🇵🇦' },
	{ name: 'Papua Nuova Guinea', dial_code: '+675', code: 'PG', flag: '🇵🇬' },
	{ name: 'Paraguay', dial_code: '+595', code: 'PY', flag: '🇵🇾' },
	{ name: 'Perù', dial_code: '+51', code: 'PE', flag: '🇵🇪' },
	{ name: 'Filippine', dial_code: '+63', code: 'PH', flag: '🇵🇭' },
	{ name: 'Polonia', dial_code: '+48', code: 'PL', flag: '🇵🇱' },
	{ name: 'Portogallo', dial_code: '+351', code: 'PT', flag: '🇵🇹' },
	{ name: 'Porto Rico', dial_code: '+1939', code: 'PR', flag: '🇵🇷' },
	{ name: 'Qatar', dial_code: '+974', code: 'QA', flag: '🇶🇦' },
	{ name: 'Romania', dial_code: '+40', code: 'RO', flag: '🇷🇴' },
	{ name: 'Russia', dial_code: '+7', code: 'RU', flag: '🇷🇺' },
	{ name: 'Ruanda', dial_code: '+250', code: 'RW', flag: '🇷🇼' },
	{ name: 'Réunion', dial_code: '+262', code: 'RE', flag: '🇷🇪' },
	{ name: 'Saint Barthélemy', dial_code: '+590', code: 'BL', flag: '🇧🇱' },
	{ name: 'Sant\'Elena, Ascensione e Tristan da Cunha', dial_code: '+290', code: 'SH', flag: '🇸🇭' },
	{ name: 'Saint Kitts e Nevis', dial_code: '+1869', code: 'KN', flag: '🇰🇳' },
	{ name: 'Santa Lucia', dial_code: '+1758', code: 'LC', flag: '🇱🇨' },
	{ name: 'Saint Martin', dial_code: '+590', code: 'MF', flag: '🇲🇫' },
	{ name: 'Saint-Pierre e Miquelon', dial_code: '+508', code: 'PM', flag: '🇵🇲' },
	{ name: 'Saint Vincent e Grenadine', dial_code: '+1784', code: 'VC', flag: '🇻🇨' },
	{ name: 'Samoa', dial_code: '+685', code: 'WS', flag: '🇼🇸' },
	{ name: 'San Marino', dial_code: '+378', code: 'SM', flag: '🇸🇲' },
	{ name: 'São Tomé e Príncipe', dial_code: '+239', code: 'ST', flag: '🇸🇹' },
	{ name: 'Arabia Saudita', dial_code: '+966', code: 'SA', flag: '🇸🇦' },
	{ name: 'Senegal', dial_code: '+221', code: 'SN', flag: '🇸🇳' },
	{ name: 'Serbia', dial_code: '+381', code: 'RS', flag: '🇷🇸' },
	{ name: 'Seychelles', dial_code: '+248', code: 'SC', flag: '🇸🇨' },
	{ name: 'Sierra Leone', dial_code: '+232', code: 'SL', flag: '🇸🇱' },
	{ name: 'Singapore', dial_code: '+65', code: 'SG', flag: '🇸🇬' },
	{ name: 'Slovacchia', dial_code: '+421', code: 'SK', flag: '🇸🇰' },
	{ name: 'Slovenia', dial_code: '+386', code: 'SI', flag: '🇸🇮' },
	{ name: 'Isole Salomone', dial_code: '+677', code: 'SB', flag: '🇸🇧' },
	{ name: 'Somalia', dial_code: '+252', code: 'SO', flag: '🇸🇴' },
	{ name: 'Sudafrica', dial_code: '+27', code: 'ZA', flag: '🇿🇦' },
	{ name: 'Georgia del Sud e Isole Sandwich Australi', dial_code: '+500', code: 'GS', flag: '🇬🇸' },
	{ name: 'Spagna', dial_code: '+34', code: 'ES', flag: '🇪🇸' },
	{ name: 'Sri Lanka', dial_code: '+94', code: 'LK', flag: '🇱🇰' },
	{ name: 'Sudan', dial_code: '+249', code: 'SD', flag: '🇸🇩' },
	{ name: 'Sudan del Sud', dial_code: '+211', code: 'SS', flag: '🇸🇸' },
	{ name: 'Suriname', dial_code: '+597', code: 'SR', flag: '🇸🇷' },
	{ name: 'Svalbard e Jan Mayen', dial_code: '+47', code: 'SJ', flag: '🇸🇯' },
	{ name: 'Svezia', dial_code: '+46', code: 'SE', flag: '🇸🇪' },
	{ name: 'Svizzera', dial_code: '+41', code: 'CH', flag: '🇨🇭' },
	{ name: 'Siria', dial_code: '+963', code: 'SY', flag: '🇸🇾' },
	{ name: 'Taiwan', dial_code: '+886', code: 'TW', flag: '🇹🇼' },
	{ name: 'Tagikistan', dial_code: '+992', code: 'TJ', flag: '🇹🇯' },
	{ name: 'Tanzania', dial_code: '+255', code: 'TZ', flag: '🇹🇿' },
	{ name: 'Thailandia', dial_code: '+66', code: 'TH', flag: '🇹🇭' },
	{ name: 'Timor Est', dial_code: '+670', code: 'TL', flag: '🇹🇱' },
	{ name: 'Togo', dial_code: '+228', code: 'TG', flag: '🇹🇬' },
	{ name: 'Tokelau', dial_code: '+690', code: 'TK', flag: '🇹🇰' },
	{ name: 'Tonga', dial_code: '+676', code: 'TO', flag: '🇹🇴' },
	{ name: 'Trinidad e Tobago', dial_code: '+1868', code: 'TT', flag: '🇹🇹' },
	{ name: 'Tunisia', dial_code: '+216', code: 'TN', flag: '🇹🇳' },
	{ name: 'Turchia', dial_code: '+90', code: 'TR', flag: '🇹🇷' },
	{ name: 'Turkmenistan', dial_code: '+993', code: 'TM', flag: '🇹🇲' },
	{ name: 'Isole Turks e Caicos', dial_code: '+1649', code: 'TC', flag: '🇹🇨' },
	{ name: 'Tuvalu', dial_code: '+688', code: 'TV', flag: '🇹🇻' },
	{ name: 'Uganda', dial_code: '+256', code: 'UG', flag: '🇺🇬' },
	{ name: 'Ucraina', dial_code: '+380', code: 'UA', flag: '🇺🇦' },
	{ name: 'Emirati Arabi Uniti', dial_code: '+971', code: 'AE', flag: '🇦🇪' },
	{ name: 'Uruguay', dial_code: '+598', code: 'UY', flag: '🇺🇾' },
	{ name: 'Uzbekistan', dial_code: '+998', code: 'UZ', flag: '🇺🇿' },
	{ name: 'Vanuatu', dial_code: '+678', code: 'VU', flag: '🇻🇺' },
	{ name: 'Venezuela', dial_code: '+58', code: 'VE', flag: '🇻🇪' },
	{ name: 'Vietnam', dial_code: '+84', code: 'VN', flag: '🇻🇳' },
	{ name: 'Isole Vergini Britanniche', dial_code: '+1284', code: 'VG', flag: '🇻🇬' },
	{ name: 'Isole Vergini Americane', dial_code: '+1340', code: 'VI', flag: '🇻🇮' },
	{ name: 'Wallis e Futuna', dial_code: '+681', code: 'WF', flag: '🇼🇫' },
	{ name: 'Yemen', dial_code: '+967', code: 'YE', flag: '🇾🇪' },
	{ name: 'Zambia', dial_code: '+260', code: 'ZM', flag: '🇿🇲' },
	{ name: 'Zimbabwe', dial_code: '+263', code: 'ZW', flag: '🇿🇼' },
	{ name: 'Isole Åland', dial_code: '+358', code: 'AX', flag: '🇦🇽' },
].sort((a, b) => a.name.localeCompare(b.name));
