# supabase/config.toml

# Configurazione esplicita per le Edge Functions di Supabase.
# Questo file elimina ogni ambiguità durante il processo di deployment.

[functions]
  # Specifica la directory dove si trovano tutte le tue funzioni.
  # Questo assicura che il deployer trovi 'health-check', 'generate-n8n-workflow', ecc.
  functions_path = "supabase/functions"

  # **QUESTA È LA RIGA PIÙ IMPORTANTE**
  # Specifica esplicitamente il percorso del file import_map.json.
  # Senza questo, il bundler potrebbe non trovare le dipendenze (@google/genai, serve),
  # causando un fallimento silenzioso del deploy e il conseguente errore 404.
  import_map = "supabase/import_map.json"
