name: Daily Documentation Update

on:
  # Manual trigger
  workflow_dispatch:
  
  # Automatic daily at 23:00 CEST (21:00 UTC)
  schedule:
    - cron: '0 21 * * *'
  
  # Trigger on push to main (optional)
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'supabase/migrations/**'

permissions:
  contents: write

jobs:
  update-documentation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci --only=production || npm install --production
      
      - name: Generate Documentation Report
        run: node scripts/generate-docs-report.js
      
      - name: Commit and Push Changes
        run: |
          git config --local user.name "Documentation Bot"
          git config --local user.email "bot@crm-ai.dev"
          git add MASTER_ROADMAP_OCT_2025.md TECHNICAL_ARCHITECTURE.md docs/daily-reports/ || true
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "docs: automated daily update $(date +%Y-%m-%d) [skip ci]" &&
            git push
          )